### ISSUE TITLE
NODE_MODULE_VERSION 72. This version of Node.js requires NODE_MODULE_VERSION 57. Please try re-compiling or re-installing

### ISSUE THREAD

**Issue by BartManX** [NeoxaChain/kawpow-pool#1]
pool@neox:~/kawpow-pool$ node ./init.js
/home/pool/kawpow-pool/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: The module '/home/pool/kawpow-pool/node_modules/bignum/build/Release/bignum.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at bindings (/home/pool/kawpow-pool/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/home/pool/kawpow-pool/node_modules/bignum/index.js:1:92)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)

**Comment by PvtSec** [comment]
Try starting it with:
```bash
~/.nvm/versions/node/<your version>/bin/node init.js
```

**Comment by JeffNeff** [comment]
same issue.. having issues getting past this

**Comment by JeffNeff** [comment]
Running `npm rebuild` fixed the issue

**Comment by spollock28269** [comment]
I had to use this solution to get around it...
delete node_modules folder completely:     rm -rf node_modules
Clear npm cache:                                          npm cache clear
After that run:                                               npm i

**Comment by BartManX** [comment]
this will fix it:
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
source ~/.profile
nvm install  12.13.0
