### ISSUE TITLE
Install but issue when starting

### ISSUE THREAD

**Issue by bpatelTWO** [NeoxaChain/kawpow-pool#14]
This is the issue I have. Any suggestions. Seems I'm finally close

pool@neoxa:~/kawpow-pool$ node ./init.js
[2022-09-24T17:03:39.952Z] [debug] [system] [init.js] : POSIX Connection Limit (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
[2022-09-24T17:03:40.212Z] [debug] [system] [init.js] : Master
[2022-09-24T17:03:40.410Z] [debug] [system] [SwitchingSetup[:1]] : Loading last proxy state from redis
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)
Emitted 'error' event on RedisClient instance at:
    at RedisClient.on_error (/home/pool/kawpow-pool/node_modules/redis/index.js:342:14)
    at Socket.<anonymous> (/home/pool/kawpow-pool/node_modules/redis/index.js:223:14)
    at Socket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}

**Comment by Ravmtl** [comment]
@bpatelTWO you should recheck your Redis database connectivity setup.  Make sure the Redis service is running (if on the same server or another), the redis userid/password combinaison, etc.

Hope this help.
