### ISSUE TITLE
How to proceed with this

### ISSUE THREAD

**Issue by caodaye** [NeoxaChain/kawpow-pool#3]
pool@ecs-MMXaW:~/kawpow-pool/pool_configs$ node ./init.js
module.js:549
    throw err;
    ^

Error: Cannot find module '/home/pool/kawpow-pool/pool_configs/init.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
pool@ecs-MMXaW:~/kawpow-pool/pool_configs$

**Comment by twystidceed** [comment]
you need to back up one directory to kapow-pool where init.js is located ..
