### ISSUE TITLE
How to solve this please

### ISSUE THREAD

**Issue by caodaye** [NeoxaChain/kawpow-pool#8]
pool@1014823031:~/kawpow-pool$ node ./init.js
[2022-09-06T11:11:42.366Z] [debug] [system] [init.js] : POSIX Connection Limit (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
[2022-09-06T11:11:42.625Z] [debug] [system] [init.js] : Master
[2022-09-06T11:11:42.815Z] [debug] [system] [SwitchingSetup[:1]] : Loading last proxy state from redis
[2022-09-06T11:11:42.825Z] [debug] [neoxamainnet] [ShareProcessor [:0]] : Share processing setup with redis (127.0.0.1:6379)
[2022-09-06T11:11:42.825Z] [info] [neoxamainnet] [Pool [:1]] : Could not start pool, error with init batch RPC call: {"type":"offline","message":"connect ECONNREFUSED 127.0.0.1:8888"}
[2022-09-06T11:11:44.380Z] [info] [system] [CLI] : CLI listening on 127.0.0.1:17117
[2022-09-06T11:11:44.572Z] [info] [system] [PaymentProcessing] : PP> Payment processor worker started
[2022-09-06T11:11:44.574Z] [info] [system] [PaymentProcessing] : PP> Enabled neoxamainnet for payment processing
[2022-09-06T11:11:44.578Z] [debug] [neoxamainnet] [PaymentProcessor] : PP> FEE % = NEOXAMAINNET
[2022-09-06T11:11:44.579Z] [debug] [neoxamainnet] [PaymentProcessor] : PP> minPayment = NEOXAMAINNET
[2022-09-06T11:11:44.579Z] [debug] [neoxamainnet] [PaymentProcessor] : PP> paymentInterval = NEOXAMAINNET
[2022-09-06T11:11:44.579Z] [debug] [neoxamainnet] [PaymentProcessor] : PP> Validating address and balance
[2022-09-06T11:11:44.583Z] [info] [system] [Website] : Starting Website module
[2022-09-06T11:11:44.584Z] [info] [system] [Stats] : Starting Stats Module...
[2022-09-06T11:11:44.584Z] [debug] [system] [Stats] : Initializing Stats Redis...
[2022-09-06T11:11:44.586Z] [debug] [system] [Stats] : Initializing Stats History...
[2022-09-06T11:11:44.586Z] [error] [neoxamainnet] [PaymentProcessor] : PP>ERROR> Error with payment processing daemon {"type":"offline","message":"connect ECONNREFUSED 127.0.0.1:8888"}
[2022-09-06T11:11:44.586Z] [debug] [system] [Website] : Loaded EXAMPLE news_example.html
[2022-09-06T11:11:44.586Z] [error] [neoxamainnet] [PaymentProcessor] : PP>ERROR> There was error during payment processor setup true
[2022-09-06T11:11:44.587Z] [debug] [system] [PaymentProcessing] : PP> Payment processor initialized. Setup results false
[2022-09-06T11:11:44.591Z] [info] [system] [Website] : WEBSITE> Attempting to start Website on 0.0.0.0:8080
[2022-09-06T11:11:44.598Z] [info] [system] [Website] : WEBSITE> Website started on 0.0.0.0:8080
[2022-09-06T11:11:44.609Z] [error] [system] [Website] : WEBSITE> Could not dumpprivkey for neoxamainnet , err = {"type":"offline","message":"connect ECONNREFUSED 127.0.0.1:8888"}
(node:11312) [DEP0001] DeprecationWarning: OutgoingMessage.flush is deprecated. Use flushHeaders instead.
[2022-09-06T11:12:42.633Z] [error] [neoxamainnet] [PaymentProcessor] : PP>ERROR> Error with RPC call getmininginfo {"type":"offline","message":"connect ECONNREFUSED 127.0.0.1:8888"}

**Comment by spollock28269** [comment]
I had the same issue. I changed the ports in neoxa.json as follows for paymentProcessing and daemons.  Also be sure to use the same user/pass you have in ./neoxa/neoxa.conf

 "paymentProcessing": {
        "enabled": true,
        "schema": "PROP",
        "paymentInterval": 300,
        "minimumPayment": 5,
        "maxBlocksPerPayment": 50000,
        "minConf": 30,
        "coinPrecision": 8,
        "daemon": {
            "host": "127.0.0.1",
            "port": 9766,
            "user": "xxxxxxx",
            "password": "xxxxxxx"


"daemons": [
        {
            "host": "127.0.0.1",
            "port": 9766,
            "user": "xxxxxxx",
            "password": "xxxxxxx"

**Comment by cristianvsl** [comment]
I have a complete guide on how to setup neoxa pool fully working for those who are interested! Cheers

**Comment by dogemackenzie** [comment]
Im interested in your guide. I got as far as the person above did. I had to recompile/update Node, etc.

**Comment by cristianvsl** [comment]
I can do it for you now and you’ll have a working pool in about 2 hours

I have one miner connected to my pool, check it out: https://neoxa.mining-pub.com/workers/GdyYS1x5VzMsWMZuZKgX446qPjwP1LeKkW.ST

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by dogemackenzie** [comment]
This is the error im seeing

[2022-09-23T19:48:14.562Z] [info] [system] [Website] : WEBSITE> Attempting to start Website on 0.0.0.0:8080
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at process.target._send (internal/child_process.js:806:20)
    at process.target.send (internal/child_process.js:676:19)
    at sendHelper (internal/cluster/utils.js:22:15)
    at send (internal/cluster/child.js:190:10)
    at EventEmitter.cluster._setupWorker (internal/cluster/child.js:43:3)
    at initializeClusterIPC (internal/bootstrap/pre_execution.js:336:13)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:57:3)
    at internal/main/run_main_module.js:7:1
Emitted 'error' event on Worker instance at:
    at process.<anonymous> (internal/cluster/worker.js:27:12)
    at process.emit (events.js:210:5)
    at internal/child_process.js:810:39
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  errno: 'EPIPE',
  code: 'EPIPE',

**Comment by bpatelTWO** [comment]
> I have a complete guide on how to setup neoxa pool fully working for those who are interested! Cheers

I would love a copy of the install guide. Been fighting it for 2-3 days,

**Comment by cristianvsl** [comment]
> 

cristian.vsl@outlook.com contact me

**Comment by dogemackenzie** [comment]
> > I have a complete guide on how to setup neoxa pool fully working for those who are interested! Cheers
> 
> I would love a copy of the install guide. Been fighting it for 2-3 days,

Agreed, its a hit miss. I either get the web server running, but the pool doesnt come up. Or the other way around.

In your case, try the following

npm rebuild
npm i

node ./init.js

**Comment by cristianvsl** [comment]
> > > I have a complete guide on how to setup neoxa pool fully working for those who are interested! Cheers
> > 
> > 
> > I would love a copy of the install guide. Been fighting it for 2-3 days,
> 
> Agreed, its a hit miss. I either get the web server running, but the pool doesnt come up. Or the other way around.
> 
> In your case, try the following
> 
> npm rebuild npm i
> 
> node ./init.js

That's not the problem :)

**Comment by cristianvsl** [comment]
@dogemackenzie Did you managed to have the pool up and running with my guides?

**Comment by dogemackenzie** [comment]
> @dogemackenzie Did you managed to have the pool up and running with my guides?

Nope, but it got me further than i was before.

**Comment by cristianvsl** [comment]
What is the problem? Use Ubuntu 22.04.1 As I am currently building for someone the neoxa pool and I had problems with Ubuntu 22.04 LTS that he installed on the server.

With Ubuntu 22.04.1 you’ll be able to build without issues.

One issue will be the repository of ppa:bitcoin/bitcoin. Ignore that. It will work without it

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by dogemackenzie** [comment]
Ok ill give that a shot. I havent done a new build with v22, but will later today
On Saturday, September 24, 2022 14:27 PDT, cristianvsl ***@***.***> wrote:
 
 What is the problem? Use Ubuntu 22.04.1 As I am currently building for someone the neoxa pool and I had problems with Ubuntu 22.04 LTS that he installed on the server.

With Ubuntu 22.04.1 you’ll be able to build without issues.

One issue will be the repository of ppa:bitcoin/bitcoin. Ignore that. It will work without it

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
